### ISSUE TITLE
Move to "Quantifier"

### ISSUE THREAD

**Issue by jaclynsaunders** [BCODMO/bcodmont#10]
As the following are all quantitative properties, these can all be moved from Physical/Characteristic to Quantifiers to stay consistent with the model. The UI has been adjusted to handle this move.

ID | AL rdfs:label@en
-- | --
PATO:0001842 | acidity
PATO:0001430 | alkalinity
PATO:0001585 | conductivity
PATO:0001019 | density
BSM:0310003 | potential density
PATO:0001595 | depth
PATO:0001757 | electrical conductivity
BSM:0310001 | electrical resistivity
BSM:0310002 | fugacity
PATO:0000973 | porosity
PATO:0001025 | pressure
PATO:0085001 | salinity
PATO:0000146 | temperature
BSM:0310004 | potential temperature
BSM:0310005 | turbidity

**Comment by kaiiam** [comment]
Thanks @jaclynsaunders will do. After doing so the remaining terms in the ` Physical/Characteristic` module will only be the color hierarchy.  I think it might reasonable to move those over as well but we can discuss if that's desired or not.

**Comment by kaiiam** [comment]
Done for now see https://github.com/BCODMO/bcodmont/blob/main/src/ontology/BCODMO_SM/quantifiers/quantifiers.owl, but TBD if we move the color terms over or not.

**Comment by jaclynsaunders** [comment]
As color is a descriptive characteristic as opposed to a quantifiable feature, please leave color in the current location. There will be more descriptive characteristics to add in later.

**Comment by kaiiam** [comment]
Sounds good thanks @jaclynsaunders  will close this now.
