### ISSUE TITLE
SKOS conventions for Synonyms in doccumentation

### ISSUE THREAD

**Issue by kaiiam** [BCODMO/bcodmont#2]
For the documentation section on [synonyms](https://github.com/BCODMO/bcodmont/blob/main/docs/technical-documentation.md#synonyms) @jaclynsaunders asked if I could:

> add a bit more to this? Maybe link out to docs on these conventions.

@jaclynsaunders unfortunately I wasn't able to find any obvious docs explaining this when I wrote it. I tried to come up with concise simple examples to explain it as best I could base on many conversation with OBO people. I think this section gives concise example to understand the concepts, but if it's not clear then let me know more specifically how I can improve it. I could try writing out a more verbose explanation based on my understanding of those SKOS concepts.

**Comment by jaclynsaunders** [comment]
Sounds good. It is a clear description and can stand alone.

**Comment by kaiiam** [comment]
OK, thanks @jaclynsaunders when I get a chance I'll give it another look over and see if I can improve it or find something to link to, if not I'll just close this issue.
